#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

APP_NAME="PopupEditor"
BUILD_DIR=".build/debug"
APP_BUNDLE="$BUILD_DIR/$APP_NAME.app"
LOG_FILE="$SCRIPT_DIR/debug.log"

# Kill any existing instance
echo "==> Killing existing instances..."
pkill -f "$APP_NAME.app/Contents/MacOS/$APP_NAME" 2>/dev/null || true
pkill -f ".build/debug/$APP_NAME" 2>/dev/null || true
sleep 0.5

echo "==> Generating version info..."

# Get git info
if git rev-parse --git-dir > /dev/null 2>&1; then
    COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
    BUILD_DATE=$(date +"%Y-%m-%d")
else
    COMMIT_HASH="unknown"
    BUILD_DATE=$(date +"%Y-%m-%d")
fi

# Generate Version.swift
cat > Sources/PopupEditor/Version.swift << EOF
// Auto-generated by build.sh - do not edit manually
struct AppVersion {
    static let commitHash = "$COMMIT_HASH"
    static let buildDate = "$BUILD_DATE"
    static let version: String = "\(commitHash) (\(buildDate))-debug"
}
EOF

echo "    Version: $COMMIT_HASH ($BUILD_DATE)-debug"

echo "==> Building debug..."
if ! swift build -c debug; then
    echo "Build failed, clearing cache and retrying..."
    rm -rf .build
    swift build -c debug
fi

echo "==> Creating debug app bundle..."

# Clean previous bundle
rm -rf "$APP_BUNDLE"

# Create bundle structure
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Copy executable
cp "$BUILD_DIR/$APP_NAME" "$APP_BUNDLE/Contents/MacOS/"

# Copy resource bundle (Bundle.module looks for the .bundle next to the executable)
if [ -d "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle" ]; then
    cp -R "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle" "$APP_BUNDLE/Contents/MacOS/"
fi

# Create Info.plist
cat > "$APP_BUNDLE/Contents/Info.plist" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>com.popupeditor.app.debug</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0-debug</string>
    <key>CFBundleVersion</key>
    <string>$COMMIT_HASH</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

# Create PkgInfo
echo -n "APPL????" > "$APP_BUNDLE/Contents/PkgInfo"

echo "==> Build complete!"
echo "    App bundle: $APP_BUNDLE"
echo ""

# Clear log file
> "$LOG_FILE"

echo "==> Launching app with logging..."
echo "    Logs: $LOG_FILE"
echo "    Press Ctrl+C to stop"
echo ""
echo "========== APP OUTPUT =========="

# Run the app directly (not via open) to capture stdout/stderr
# Tee to both terminal and log file
"$APP_BUNDLE/Contents/MacOS/$APP_NAME" 2>&1 | tee "$LOG_FILE"

