# Homebrew formula for PopupEditor
# To use this formula, create your own tap:
#   1. Create a GitHub repo named "homebrew-tap"
#   2. Copy this file to Formula/popupeditor.rb in that repo
#   3. Update the url and sha256 below with your release tarball
#   4. Run: brew tap yourusername/tap && brew install popupeditor

class Popupeditor < Formula
  desc "A floating Monaco editor popup for quick text editing"
  homepage "https://github.com/YOURUSERNAME/popupeditor"
  # Update this URL to point to your release tarball
  url "https://github.com/YOURUSERNAME/popupeditor/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "UPDATE_WITH_ACTUAL_SHA256"
  license "MIT"

  depends_on xcode: ["14.0", :build]
  depends_on macos: :ventura

  def install
    # Generate version info
    commit = `git rev-parse --short HEAD 2>/dev/null`.strip
    commit = "release" if commit.empty?
    build_date = Time.now.strftime("%Y-%m-%d")

    File.write("Sources/PopupEditor/Version.swift", <<~SWIFT)
      // Auto-generated by Homebrew
      struct AppVersion {
          static let commitHash = "#{commit}"
          static let buildDate = "#{build_date}"
          static let version: String = "\\(commitHash) (\\(buildDate))"
      }
    SWIFT

    system "swift", "build", "-c", "release", "--disable-sandbox"
    
    # Create app bundle
    app_bundle = "PopupEditor.app"
    mkdir_p "#{app_bundle}/Contents/MacOS"
    mkdir_p "#{app_bundle}/Contents/Resources"
    
    cp ".build/release/PopupEditor", "#{app_bundle}/Contents/MacOS/"
    
    # Copy resources if they exist
    resources_bundle = ".build/release/PopupEditor_PopupEditor.bundle"
    if File.directory?(resources_bundle)
      cp_r Dir["#{resources_bundle}/*"], "#{app_bundle}/Contents/Resources/"
    end

    # Create Info.plist
    File.write("#{app_bundle}/Contents/Info.plist", <<~PLIST)
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>CFBundleExecutable</key>
          <string>PopupEditor</string>
          <key>CFBundleIdentifier</key>
          <string>com.popupeditor.app</string>
          <key>CFBundleName</key>
          <string>PopupEditor</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleShortVersionString</key>
          <string>#{version}</string>
          <key>CFBundleVersion</key>
          <string>#{commit}</string>
          <key>LSMinimumSystemVersion</key>
          <string>13.0</string>
          <key>LSUIElement</key>
          <true/>
          <key>NSHighResolutionCapable</key>
          <true/>
      </dict>
      </plist>
    PLIST

    File.write("#{app_bundle}/Contents/PkgInfo", "APPL????")

    # Install to Caskroom-style location
    prefix.install app_bundle
  end

  def post_install
    # Link to Applications
    system "ln", "-sf", "#{prefix}/PopupEditor.app", "/Applications/PopupEditor.app"
  end

  def caveats
    <<~EOS
      PopupEditor has been installed to /Applications.

      To start the app:
        open /Applications/PopupEditor.app

      To start at login, add it to:
        System Settings → General → Login Items

      Keyboard shortcuts:
        Cmd+Shift+E  - Toggle editor
        Cmd+R        - Change language
        Cmd+Enter    - Paste into previous app
        Cmd+Esc      - Clear and close
        Esc          - Close

      Note: For Cmd+Enter to work, grant Accessibility permissions in:
        System Settings → Privacy & Security → Accessibility
    EOS
  end

  test do
    assert_predicate prefix/"PopupEditor.app/Contents/MacOS/PopupEditor", :exist?
  end
end

