// Auto-generated by build.sh - do not edit manually
struct AppVersion {
    static let commitHash = "06a4a47"
    static let buildDate = "2025-12-09"
    static let version: String = "\(commitHash) (\(buildDate))"
}
